name: 'build and publish for docker registry'
on:
    push:
        branches: [ master ]
jobs:
    build-publish:
        name: 'Build & Publish'
        runs-on: ubuntu-latest
        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v2
            -   name: "Set up QEMU"
                uses: docker/setup-qemu-action@v3
            -   name: "Set up Docker Buildx"
                uses: docker/setup-buildx-action@v3
            -   name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    registry: ${{ secrets.REGISTRY_URL }}
                    username: ${{ secrets.REGISTRY_USERNAME }}
                    password: ${{ secrets.REGISTRY_TOKEN }}
            -   name: "Build"
                uses: docker/build-push-action@v5
                with:
                    context: ./src/
                    file: ./src/Dockerfile
                    push: true
                    tags: |
                        ${{ secrets.REGISTRY_URL }}/pepegov/app:latest
                    secrets: |
                        "ASPNETCORE_ENVIRONMENT=Release"
                    build-args: |
                        build_mode=Release