version: '3.8'

services:
  replica1:
    image: mongo
    hostname: mongo1
    container_name: mongo-replica-1
    networks:
      - network
    ports:
      - 27117:27017
    volumes:
      - ./keys:/keys
      - ./scripts:/scripts
      - replica1_db:/data/db
      - replica1_config:/data/configdb
    depends_on:
      - replica2
      - replica3
    links:
      - replica2
      - replica3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/keys/key", "--auth",  "--bind_ip_all", "--replSet", "mongo_replica" ]

  replica2:
    image: mongo
    hostname: mongo2
    container_name: mongo-replica-2
    networks:
      - network
    ports:
      - 27118:27017
    volumes:
      - ./keys:/keys
      - ./scripts:/scripts
      - replica2_db:/data/db
      - replica2_config:/data/configdb
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/keys/key", "--auth",  "--bind_ip_all", "--replSet", "mongo_replica" ]
    

  replica3:
    image: mongo
    hostname: mongo3
    container_name: mongo-replica-3
    networks:
      - network
    ports:
      - 27119:27017
    volumes:
      - ./keys:/keys
      - ./scripts:/scripts
      - replica3_db:/data/db
      - replica3_config:/data/configdb
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--keyFile", "/keys/key", "--auth",  "--bind_ip_all", "--replSet", "mongo_replica" ]


volumes:
  replica1_db:
  replica1_config:

  replica2_db:
  replica2_config:

  replica3_db:
  replica3_config:

networks:
  network:
    driver: bridge
