version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: J5vd_x91mK7aaa
    volumes:
      - .:/data/db
    ports:
      - 27017:27017
