version: '3'
services:
  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    restart: always
    env_file:
      - .env
    ports:
      - 9020:80
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice
      - onlyoffice_lib:/var/lib/onlyoffice

volumes:
  onlyoffice_log:
  onlyoffice:
  onlyoffice_lib: