version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo-standart
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/data/db
    ports:
      - 27016:27017
