version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    container_name: minio-standalone
    restart: always
    env_file:
      - .env
    command: server --console-address ":9001" /data

volumes:
  minio_storage: