version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo-standalone
    restart: always
    env_file:
      - .env
    volumes:
      - mongo_db:/data/db
    ports:
      - 27016:27017

volumes:
  mongo_db:

