version: "2.1"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    tty: true
    hostname: rabbitmq
    container_name: rabbitmq-masstransit
    restart: always
    env_file:
      - .env
    volumes:
      - rabbitmq-masstransit_db:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  rabbitmq-masstransit_db: