version: "2.1"
services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    tty: true
    hostname: rabbitmq
    container_name: rabbitmq-masstransit
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./data:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
